name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  checkDist:
    name: CheckDist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check if generated code is correct
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: mv dist/index.js dist/index.js.new
      - run: npm ci
      - run: npm run build
      - run: diff dist/index.js dist/index.js.new
